// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/paymentorder"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sku"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (pou *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	pou.mutation.Where(ps...)
	return pou
}

// SetUpdatedAt sets the "updated_at" field.
func (pou *PaymentOrderUpdate) SetUpdatedAt(t time.Time) *PaymentOrderUpdate {
	pou.mutation.SetUpdatedAt(t)
	return pou
}

// SetDeletedAt sets the "deleted_at" field.
func (pou *PaymentOrderUpdate) SetDeletedAt(t time.Time) *PaymentOrderUpdate {
	pou.mutation.SetDeletedAt(t)
	return pou
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableDeletedAt(t *time.Time) *PaymentOrderUpdate {
	if t != nil {
		pou.SetDeletedAt(*t)
	}
	return pou
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pou *PaymentOrderUpdate) ClearDeletedAt() *PaymentOrderUpdate {
	pou.mutation.ClearDeletedAt()
	return pou
}

// SetUserID sets the "user_id" field.
func (pou *PaymentOrderUpdate) SetUserID(i int) *PaymentOrderUpdate {
	pou.mutation.SetUserID(i)
	return pou
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableUserID(i *int) *PaymentOrderUpdate {
	if i != nil {
		pou.SetUserID(*i)
	}
	return pou
}

// SetSkuID sets the "sku_id" field.
func (pou *PaymentOrderUpdate) SetSkuID(i int) *PaymentOrderUpdate {
	pou.mutation.SetSkuID(i)
	return pou
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableSkuID(i *int) *PaymentOrderUpdate {
	if i != nil {
		pou.SetSkuID(*i)
	}
	return pou
}

// SetProvider sets the "provider" field.
func (pou *PaymentOrderUpdate) SetProvider(s string) *PaymentOrderUpdate {
	pou.mutation.SetProvider(s)
	return pou
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableProvider(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetProvider(*s)
	}
	return pou
}

// SetSessionID sets the "session_id" field.
func (pou *PaymentOrderUpdate) SetSessionID(s string) *PaymentOrderUpdate {
	pou.mutation.SetSessionID(s)
	return pou
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableSessionID(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetSessionID(*s)
	}
	return pou
}

// ClearSessionID clears the value of the "session_id" field.
func (pou *PaymentOrderUpdate) ClearSessionID() *PaymentOrderUpdate {
	pou.mutation.ClearSessionID()
	return pou
}

// SetAmount sets the "amount" field.
func (pou *PaymentOrderUpdate) SetAmount(i int64) *PaymentOrderUpdate {
	pou.mutation.ResetAmount()
	pou.mutation.SetAmount(i)
	return pou
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableAmount(i *int64) *PaymentOrderUpdate {
	if i != nil {
		pou.SetAmount(*i)
	}
	return pou
}

// AddAmount adds i to the "amount" field.
func (pou *PaymentOrderUpdate) AddAmount(i int64) *PaymentOrderUpdate {
	pou.mutation.AddAmount(i)
	return pou
}

// SetCurrency sets the "currency" field.
func (pou *PaymentOrderUpdate) SetCurrency(s string) *PaymentOrderUpdate {
	pou.mutation.SetCurrency(s)
	return pou
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableCurrency(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetCurrency(*s)
	}
	return pou
}

// SetStatus sets the "status" field.
func (pou *PaymentOrderUpdate) SetStatus(pa paymentorder.Status) *PaymentOrderUpdate {
	pou.mutation.SetStatus(pa)
	return pou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableStatus(pa *paymentorder.Status) *PaymentOrderUpdate {
	if pa != nil {
		pou.SetStatus(*pa)
	}
	return pou
}

// SetUser sets the "user" edge to the User entity.
func (pou *PaymentOrderUpdate) SetUser(u *User) *PaymentOrderUpdate {
	return pou.SetUserID(u.ID)
}

// SetSku sets the "sku" edge to the Sku entity.
func (pou *PaymentOrderUpdate) SetSku(s *Sku) *PaymentOrderUpdate {
	return pou.SetSkuID(s.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (pou *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return pou.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pou *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	pou.mutation.ClearUser()
	return pou
}

// ClearSku clears the "sku" edge to the Sku entity.
func (pou *PaymentOrderUpdate) ClearSku() *PaymentOrderUpdate {
	pou.mutation.ClearSku()
	return pou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pou *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	if err := pou.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, pou.sqlSave, pou.mutation, pou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pou *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := pou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pou *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := pou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pou *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := pou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pou *PaymentOrderUpdate) defaults() error {
	if _, ok := pou.mutation.UpdatedAt(); !ok {
		if paymentorder.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.UpdateDefaultUpdatedAt()
		pou.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pou *PaymentOrderUpdate) check() error {
	if v, ok := pou.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := pou.mutation.UserID(); pou.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	if _, ok := pou.mutation.SkuID(); pou.mutation.SkuCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.sku"`)
	}
	return nil
}

func (pou *PaymentOrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	if ps := pou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pou.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pou.mutation.DeletedAt(); ok {
		_spec.SetField(paymentorder.FieldDeletedAt, field.TypeTime, value)
	}
	if pou.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pou.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := pou.mutation.SessionID(); ok {
		_spec.SetField(paymentorder.FieldSessionID, field.TypeString, value)
	}
	if pou.mutation.SessionIDCleared() {
		_spec.ClearField(paymentorder.FieldSessionID, field.TypeString)
	}
	if value, ok := pou.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pou.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pou.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := pou.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeEnum, value)
	}
	if pou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pou.mutation.SkuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.SkuTable,
			Columns: []string{paymentorder.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.SkuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.SkuTable,
			Columns: []string{paymentorder.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pou.mutation.done = true
	return n, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (pouo *PaymentOrderUpdateOne) SetUpdatedAt(t time.Time) *PaymentOrderUpdateOne {
	pouo.mutation.SetUpdatedAt(t)
	return pouo
}

// SetDeletedAt sets the "deleted_at" field.
func (pouo *PaymentOrderUpdateOne) SetDeletedAt(t time.Time) *PaymentOrderUpdateOne {
	pouo.mutation.SetDeletedAt(t)
	return pouo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableDeletedAt(t *time.Time) *PaymentOrderUpdateOne {
	if t != nil {
		pouo.SetDeletedAt(*t)
	}
	return pouo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pouo *PaymentOrderUpdateOne) ClearDeletedAt() *PaymentOrderUpdateOne {
	pouo.mutation.ClearDeletedAt()
	return pouo
}

// SetUserID sets the "user_id" field.
func (pouo *PaymentOrderUpdateOne) SetUserID(i int) *PaymentOrderUpdateOne {
	pouo.mutation.SetUserID(i)
	return pouo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableUserID(i *int) *PaymentOrderUpdateOne {
	if i != nil {
		pouo.SetUserID(*i)
	}
	return pouo
}

// SetSkuID sets the "sku_id" field.
func (pouo *PaymentOrderUpdateOne) SetSkuID(i int) *PaymentOrderUpdateOne {
	pouo.mutation.SetSkuID(i)
	return pouo
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableSkuID(i *int) *PaymentOrderUpdateOne {
	if i != nil {
		pouo.SetSkuID(*i)
	}
	return pouo
}

// SetProvider sets the "provider" field.
func (pouo *PaymentOrderUpdateOne) SetProvider(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetProvider(s)
	return pouo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableProvider(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetProvider(*s)
	}
	return pouo
}

// SetSessionID sets the "session_id" field.
func (pouo *PaymentOrderUpdateOne) SetSessionID(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetSessionID(s)
	return pouo
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableSessionID(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetSessionID(*s)
	}
	return pouo
}

// ClearSessionID clears the value of the "session_id" field.
func (pouo *PaymentOrderUpdateOne) ClearSessionID() *PaymentOrderUpdateOne {
	pouo.mutation.ClearSessionID()
	return pouo
}

// SetAmount sets the "amount" field.
func (pouo *PaymentOrderUpdateOne) SetAmount(i int64) *PaymentOrderUpdateOne {
	pouo.mutation.ResetAmount()
	pouo.mutation.SetAmount(i)
	return pouo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableAmount(i *int64) *PaymentOrderUpdateOne {
	if i != nil {
		pouo.SetAmount(*i)
	}
	return pouo
}

// AddAmount adds i to the "amount" field.
func (pouo *PaymentOrderUpdateOne) AddAmount(i int64) *PaymentOrderUpdateOne {
	pouo.mutation.AddAmount(i)
	return pouo
}

// SetCurrency sets the "currency" field.
func (pouo *PaymentOrderUpdateOne) SetCurrency(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetCurrency(s)
	return pouo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableCurrency(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetCurrency(*s)
	}
	return pouo
}

// SetStatus sets the "status" field.
func (pouo *PaymentOrderUpdateOne) SetStatus(pa paymentorder.Status) *PaymentOrderUpdateOne {
	pouo.mutation.SetStatus(pa)
	return pouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableStatus(pa *paymentorder.Status) *PaymentOrderUpdateOne {
	if pa != nil {
		pouo.SetStatus(*pa)
	}
	return pouo
}

// SetUser sets the "user" edge to the User entity.
func (pouo *PaymentOrderUpdateOne) SetUser(u *User) *PaymentOrderUpdateOne {
	return pouo.SetUserID(u.ID)
}

// SetSku sets the "sku" edge to the Sku entity.
func (pouo *PaymentOrderUpdateOne) SetSku(s *Sku) *PaymentOrderUpdateOne {
	return pouo.SetSkuID(s.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (pouo *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return pouo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pouo *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	pouo.mutation.ClearUser()
	return pouo
}

// ClearSku clears the "sku" edge to the Sku entity.
func (pouo *PaymentOrderUpdateOne) ClearSku() *PaymentOrderUpdateOne {
	pouo.mutation.ClearSku()
	return pouo
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (pouo *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	pouo.mutation.Where(ps...)
	return pouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pouo *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	pouo.fields = append([]string{field}, fields...)
	return pouo
}

// Save executes the query and returns the updated PaymentOrder entity.
func (pouo *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	if err := pouo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, pouo.sqlSave, pouo.mutation, pouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pouo *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := pouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pouo *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := pouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pouo *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := pouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pouo *PaymentOrderUpdateOne) defaults() error {
	if _, ok := pouo.mutation.UpdatedAt(); !ok {
		if paymentorder.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.UpdateDefaultUpdatedAt()
		pouo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pouo *PaymentOrderUpdateOne) check() error {
	if v, ok := pouo.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := pouo.mutation.UserID(); pouo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	if _, ok := pouo.mutation.SkuID(); pouo.mutation.SkuCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.sku"`)
	}
	return nil
}

func (pouo *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := pouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	id, ok := pouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pouo.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pouo.mutation.DeletedAt(); ok {
		_spec.SetField(paymentorder.FieldDeletedAt, field.TypeTime, value)
	}
	if pouo.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pouo.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := pouo.mutation.SessionID(); ok {
		_spec.SetField(paymentorder.FieldSessionID, field.TypeString, value)
	}
	if pouo.mutation.SessionIDCleared() {
		_spec.ClearField(paymentorder.FieldSessionID, field.TypeString)
	}
	if value, ok := pouo.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pouo.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pouo.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := pouo.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeEnum, value)
	}
	if pouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pouo.mutation.SkuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.SkuTable,
			Columns: []string{paymentorder.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.SkuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.SkuTable,
			Columns: []string{paymentorder.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: pouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pouo.mutation.done = true
	return _node, nil
}
