// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/paymentorder"
	"github.com/cloudreve/Cloudreve/v4/ent/sku"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (poc *PaymentOrderCreate) SetCreatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetCreatedAt(t)
	return poc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableCreatedAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetCreatedAt(*t)
	}
	return poc
}

// SetUpdatedAt sets the "updated_at" field.
func (poc *PaymentOrderCreate) SetUpdatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetUpdatedAt(t)
	return poc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableUpdatedAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetUpdatedAt(*t)
	}
	return poc
}

// SetDeletedAt sets the "deleted_at" field.
func (poc *PaymentOrderCreate) SetDeletedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetDeletedAt(t)
	return poc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableDeletedAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetDeletedAt(*t)
	}
	return poc
}

// SetUserID sets the "user_id" field.
func (poc *PaymentOrderCreate) SetUserID(i int) *PaymentOrderCreate {
	poc.mutation.SetUserID(i)
	return poc
}

// SetSkuID sets the "sku_id" field.
func (poc *PaymentOrderCreate) SetSkuID(i int) *PaymentOrderCreate {
	poc.mutation.SetSkuID(i)
	return poc
}

// SetProvider sets the "provider" field.
func (poc *PaymentOrderCreate) SetProvider(s string) *PaymentOrderCreate {
	poc.mutation.SetProvider(s)
	return poc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableProvider(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetProvider(*s)
	}
	return poc
}

// SetSessionID sets the "session_id" field.
func (poc *PaymentOrderCreate) SetSessionID(s string) *PaymentOrderCreate {
	poc.mutation.SetSessionID(s)
	return poc
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableSessionID(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetSessionID(*s)
	}
	return poc
}

// SetAmount sets the "amount" field.
func (poc *PaymentOrderCreate) SetAmount(i int64) *PaymentOrderCreate {
	poc.mutation.SetAmount(i)
	return poc
}

// SetCurrency sets the "currency" field.
func (poc *PaymentOrderCreate) SetCurrency(s string) *PaymentOrderCreate {
	poc.mutation.SetCurrency(s)
	return poc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableCurrency(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetCurrency(*s)
	}
	return poc
}

// SetStatus sets the "status" field.
func (poc *PaymentOrderCreate) SetStatus(pa paymentorder.Status) *PaymentOrderCreate {
	poc.mutation.SetStatus(pa)
	return poc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableStatus(pa *paymentorder.Status) *PaymentOrderCreate {
	if pa != nil {
		poc.SetStatus(*pa)
	}
	return poc
}

// SetUser sets the "user" edge to the User entity.
func (poc *PaymentOrderCreate) SetUser(u *User) *PaymentOrderCreate {
	return poc.SetUserID(u.ID)
}

// SetSku sets the "sku" edge to the Sku entity.
func (poc *PaymentOrderCreate) SetSku(s *Sku) *PaymentOrderCreate {
	return poc.SetSkuID(s.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (poc *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return poc.mutation
}

// Save creates the PaymentOrder in the database.
func (poc *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	if err := poc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, poc.sqlSave, poc.mutation, poc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (poc *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := poc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (poc *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := poc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (poc *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := poc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (poc *PaymentOrderCreate) defaults() error {
	if _, ok := poc.mutation.CreatedAt(); !ok {
		if paymentorder.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.DefaultCreatedAt()
		poc.mutation.SetCreatedAt(v)
	}
	if _, ok := poc.mutation.UpdatedAt(); !ok {
		if paymentorder.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.DefaultUpdatedAt()
		poc.mutation.SetUpdatedAt(v)
	}
	if _, ok := poc.mutation.Provider(); !ok {
		v := paymentorder.DefaultProvider
		poc.mutation.SetProvider(v)
	}
	if _, ok := poc.mutation.Currency(); !ok {
		v := paymentorder.DefaultCurrency
		poc.mutation.SetCurrency(v)
	}
	if _, ok := poc.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		poc.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (poc *PaymentOrderCreate) check() error {
	if _, ok := poc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := poc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if _, ok := poc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := poc.mutation.SkuID(); !ok {
		return &ValidationError{Name: "sku_id", err: errors.New(`ent: missing required field "PaymentOrder.sku_id"`)}
	}
	if _, ok := poc.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "PaymentOrder.provider"`)}
	}
	if _, ok := poc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if _, ok := poc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentOrder.currency"`)}
	}
	if _, ok := poc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := poc.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := poc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	if _, ok := poc.mutation.SkuID(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required edge "PaymentOrder.sku"`)}
	}
	return nil
}

func (poc *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := poc.check(); err != nil {
		return nil, err
	}
	_node, _spec := poc.createSpec()
	if err := sqlgraph.CreateNode(ctx, poc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	poc.mutation.id = &_node.ID
	poc.mutation.done = true
	return _node, nil
}

func (poc *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: poc.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	)

	if id, ok := poc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = poc.conflict
	if value, ok := poc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := poc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := poc.mutation.DeletedAt(); ok {
		_spec.SetField(paymentorder.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := poc.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := poc.mutation.SessionID(); ok {
		_spec.SetField(paymentorder.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := poc.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := poc.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := poc.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := poc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := poc.mutation.SkuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.SkuTable,
			Columns: []string{paymentorder.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (poc *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	poc.conflict = opts
	return &PaymentOrderUpsertOne{
		create: poc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (poc *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	poc.conflict = append(poc.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: poc,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsert) SetUpdatedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUpdatedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentOrderUpsert) SetDeletedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateDeletedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentOrderUpsert) ClearDeletedAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetSkuID sets the "sku_id" field.
func (u *PaymentOrderUpsert) SetSkuID(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldSkuID, v)
	return u
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateSkuID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldSkuID)
	return u
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsert) SetProvider(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProvider() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProvider)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *PaymentOrderUpsert) SetSessionID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateSessionID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *PaymentOrderUpsert) ClearSessionID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldSessionID)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsert) SetAmount(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsert) AddAmount(v int64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsert) SetCurrency(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCurrency() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v paymentorder.Status) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUpdatedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentOrderUpsertOne) SetDeletedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateDeletedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentOrderUpsertOne) ClearDeletedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetSkuID sets the "sku_id" field.
func (u *PaymentOrderUpsertOne) SetSkuID(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetSkuID(v)
	})
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateSkuID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateSkuID()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertOne) SetProvider(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProvider() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetSessionID sets the "session_id" field.
func (u *PaymentOrderUpsertOne) SetSessionID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateSessionID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *PaymentOrderUpsertOne) ClearSessionID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearSessionID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertOne) SetAmount(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertOne) AddAmount(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertOne) SetCurrency(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCurrency() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v paymentorder.Status) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *PaymentOrderCreate) SetRawID(t int) *PaymentOrderCreate {
	m.mutation.SetRawID(t)
	return m
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (pocb *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if pocb.err != nil {
		return nil, pocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pocb.builders))
	nodes := make([]*PaymentOrder, len(pocb.builders))
	mutators := make([]Mutator, len(pocb.builders))
	for i := range pocb.builders {
		func(i int, root context.Context) {
			builder := pocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pocb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := pocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pocb *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := pocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := pocb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (pocb *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	pocb.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: pocb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pocb *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	pocb.conflict = append(pocb.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: pocb,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUpdatedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentOrderUpsertBulk) SetDeletedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateDeletedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentOrderUpsertBulk) ClearDeletedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetSkuID sets the "sku_id" field.
func (u *PaymentOrderUpsertBulk) SetSkuID(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetSkuID(v)
	})
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateSkuID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateSkuID()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertBulk) SetProvider(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProvider() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetSessionID sets the "session_id" field.
func (u *PaymentOrderUpsertBulk) SetSessionID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateSessionID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *PaymentOrderUpsertBulk) ClearSessionID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearSessionID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertBulk) SetAmount(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertBulk) AddAmount(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertBulk) SetCurrency(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCurrency() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v paymentorder.Status) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
